# Generated by Django 4.2.6 on 2023-11-18 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_site', '0002_subscriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productslikes',
            options={'verbose_name': 'Лайк продукта', 'verbose_name_plural': 'Лайки продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productsraitings',
            options={'verbose_name': 'Рейтинг продукта', 'verbose_name_plural': 'Рейтинги продуктов'},
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_site.products')),
            ],
            options={
                'verbose_name': 'Корзинка',
                'verbose_name_plural': 'Корзинки',
            },
        ),
    ]
