# Generated by Django 4.0.5 on 2023-11-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0004_sliderproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
