# Generated by Django 4.0.5 on 2023-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0005_mainvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainvideo',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='mainvideo',
            name='video_image',
            field=models.ImageField(default=1, upload_to='videosImages/'),
            preserve_default=False,
        ),
    ]
